# Starter pipeline
- task: SonarCloudAnalyze@1
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#Indica que solo se ejecute en rama Main
#Lo sacamos
#trigger:
#- main

pool: 'default'
  #vmImage: ubuntu-latest
#Etapas a ejecutar el Pipeline
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

#EJECUTAR CON GRADLE se ejecuta x Tasks de forma de vista
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud_DevFoundation'
    organization: 'devops-foundation-v3'
    scannerMode: 'MSBuild'
    projectKey: 'CristianVasquezM_DevOps-Foundation-v3_Lab'
    projectName: 'cristianvasquezm'
  
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: SonarCloud Analysis
  