#Esto es un flujo de trabajo...
#Nombre de trabajo
name: Java CI with Gradle

#Eventos sobre los que trabajar. Esto es x defecto  
on:
  push:
  #Con , se agregan nuevas ramas
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
  #Se identifica sobre donde corre---
    runs-on: ubuntu-latest

    steps:
    #GitHub Actions....
    #Etiqueta q determina q GitHub Action usar...
    - uses: actions/checkout@v3
    #Nombre del paso
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      #PArametros obligatorios...
      with:
        java-version: '11'
        distribution: 'temurin'
  
    - run: 
       chmod +x gradlew
  
    - name: Build with Gradle
    #Repositorio Gradle....
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    #Aca Indicamos que generamos el JAR....
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1   
      with:
       name: JarCompilado
       path: build/libs
       
       


    

    
